# Generated by Django 4.1.3 on 2022-12-05 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionCount', models.PositiveBigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=100)),
                ('word', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=10)),
                ('image', models.CharField(max_length=200)),
                ('correctAnswerCount', models.PositiveBigIntegerField(default=0)),
                ('incorrectAnswerCount', models.PositiveBigIntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='Language',
        ),
        migrations.AddField(
            model_name='league',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.word'),
        ),
    ]
