# Generated by Django 4.1.3 on 2022-12-07 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_league_word_delete_language_league_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='language',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='word',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.league'),
        ),
    ]
