# Generated by Django 4.1.3 on 2022-12-11 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_languagescore'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='flag',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
