# Generated by Django 4.1.3 on 2022-12-11 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_league_flag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='league',
            name='flag',
        ),
    ]
