# Generated by Django 4.1.3 on 2022-12-15 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_remove_league_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='frequency',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
